"""Initial migration - create all tables

Revision ID: 26e60c6557e7
Revises: 
Create Date: 2025-09-16 21:12:25.602208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e60c6557e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='원본파일명'),
    sa.Column('file_type', sa.String(length=10), nullable=False, comment='파일타입'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='파일크기(bytes)'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='파일해시(SHA256)'),
    sa.Column('document_type', sa.String(length=50), nullable=True, comment='문서종류'),
    sa.Column('document_category', sa.String(length=100), nullable=True, comment='문서분류'),
    sa.Column('original_file_url', sa.Text(), nullable=True, comment='원본파일URL'),
    sa.Column('extracted_text_path', sa.Text(), nullable=True, comment='추출된텍스트파일경로'),
    sa.Column('markdown_path', sa.Text(), nullable=True, comment='마크다운파일경로'),
    sa.Column('processing_status', sa.String(length=20), nullable=True, comment='처리상태'),
    sa.Column('processing_error', sa.Text(), nullable=True, comment='처리오류메시지'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='처리완료일시'),
    sa.Column('extracted_text', sa.Text(), nullable=True, comment='추출된텍스트'),
    sa.Column('text_length', sa.Integer(), nullable=True, comment='텍스트길이'),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='페이지수'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI요약'),
    sa.Column('ai_keywords', sa.JSON(), nullable=True, comment='AI추출키워드'),
    sa.Column('ai_entities', sa.JSON(), nullable=True, comment='AI추출개체명'),
    sa.Column('ai_topics', sa.JSON(), nullable=True, comment='AI주제분류'),
    sa.Column('embedding_status', sa.String(length=20), nullable=True, comment='임베딩상태'),
    sa.Column('embedding_model', sa.String(length=50), nullable=True, comment='임베딩모델명'),
    sa.Column('vector_db_id', sa.String(length=100), nullable=True, comment='벡터DB아이디'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_type', 'documents', ['document_type'], unique=False)
    op.create_index('idx_file_type_status', 'documents', ['file_type', 'processing_status'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='해시화된 비밀번호'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='이름'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('company_name', sa.String(length=200), nullable=True, comment='회사명'),
    sa.Column('company_registration_no', sa.String(length=20), nullable=True, comment='사업자등록번호'),
    sa.Column('company_type', sa.String(length=50), nullable=True, comment='회사구분'),
    sa.Column('industry_sector', sa.String(length=100), nullable=True, comment='업종'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='계정활성화여부'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='이메일인증여부'),
    sa.Column('is_premium', sa.Boolean(), nullable=True, comment='프리미엄계정여부'),
    sa.Column('registration_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='가입일시'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='최종로그인일시'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_reg', 'users', ['company_registration_no'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bid_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_notice_no', sa.String(length=50), nullable=False, comment='입찰공고번호'),
    sa.Column('bid_notice_ord', sa.String(length=10), nullable=True, comment='입찰공고차수'),
    sa.Column('bid_notice_name', sa.Text(), nullable=False, comment='입찰공고명'),
    sa.Column('bid_notice_date', sa.DateTime(), nullable=True, comment='입찰공고일시'),
    sa.Column('bid_method', sa.String(length=100), nullable=True, comment='입찰방법'),
    sa.Column('bid_type', sa.String(length=50), nullable=True, comment='입찰구분'),
    sa.Column('notice_inst_code', sa.String(length=20), nullable=True, comment='공고기관코드'),
    sa.Column('notice_inst_name', sa.String(length=200), nullable=True, comment='공고기관명'),
    sa.Column('demand_inst_code', sa.String(length=20), nullable=True, comment='수요기관코드'),
    sa.Column('demand_inst_name', sa.String(length=200), nullable=True, comment='수요기관명'),
    sa.Column('bid_begin_date', sa.DateTime(), nullable=True, comment='입찰시작일시'),
    sa.Column('bid_close_date', sa.DateTime(), nullable=True, comment='입찰마감일시'),
    sa.Column('open_bid_date', sa.DateTime(), nullable=True, comment='개찰일시'),
    sa.Column('budget_amount', sa.DECIMAL(precision=15, scale=0), nullable=True, comment='예산금액'),
    sa.Column('presumpt_price', sa.DECIMAL(precision=15, scale=0), nullable=True, comment='추정가격'),
    sa.Column('bid_qualification', sa.Text(), nullable=True, comment='입찰참가자격'),
    sa.Column('bid_security_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='입찰보증금율'),
    sa.Column('contract_security_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='계약보증금율'),
    sa.Column('bid_class_no', sa.String(length=20), nullable=True, comment='입찰분류번호'),
    sa.Column('bid_class_name', sa.String(length=200), nullable=True, comment='입찰분류명'),
    sa.Column('industry_type', sa.String(length=100), nullable=True, comment='업종'),
    sa.Column('spec_doc_id', sa.Integer(), nullable=True, comment='입찰서류 문서 ID'),
    sa.Column('bid_status', sa.String(length=20), nullable=True, comment='입찰상태'),
    sa.Column('is_urgent', sa.Boolean(), nullable=True, comment='긴급공고여부'),
    sa.Column('is_international', sa.Boolean(), nullable=True, comment='국제입찰여부'),
    sa.Column('api_service', sa.String(length=50), nullable=True, comment='API 서비스 출처'),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='원본 API 응답 데이터'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['spec_doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bid_date_status', 'bid_announcements', ['bid_close_date', 'bid_status'], unique=False)
    op.create_index('idx_budget_range', 'bid_announcements', ['presumpt_price'], unique=False)
    op.create_index('idx_inst_combo', 'bid_announcements', ['notice_inst_code', 'demand_inst_code'], unique=False)
    op.create_index('idx_search_text', 'bid_announcements', ['bid_notice_name'], unique=False)
    op.create_index(op.f('ix_bid_announcements_bid_class_no'), 'bid_announcements', ['bid_class_no'], unique=False)
    op.create_index(op.f('ix_bid_announcements_bid_close_date'), 'bid_announcements', ['bid_close_date'], unique=False)
    op.create_index(op.f('ix_bid_announcements_bid_notice_date'), 'bid_announcements', ['bid_notice_date'], unique=False)
    op.create_index(op.f('ix_bid_announcements_bid_notice_no'), 'bid_announcements', ['bid_notice_no'], unique=True)
    op.create_index(op.f('ix_bid_announcements_bid_status'), 'bid_announcements', ['bid_status'], unique=False)
    op.create_index(op.f('ix_bid_announcements_demand_inst_code'), 'bid_announcements', ['demand_inst_code'], unique=False)
    op.create_index(op.f('ix_bid_announcements_id'), 'bid_announcements', ['id'], unique=False)
    op.create_index(op.f('ix_bid_announcements_is_urgent'), 'bid_announcements', ['is_urgent'], unique=False)
    op.create_index(op.f('ix_bid_announcements_notice_inst_code'), 'bid_announcements', ['notice_inst_code'], unique=False)
    op.create_index(op.f('ix_bid_announcements_presumpt_price'), 'bid_announcements', ['presumpt_price'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='청크순서'),
    sa.Column('chunk_text', sa.Text(), nullable=False, comment='청크텍스트'),
    sa.Column('chunk_length', sa.Integer(), nullable=True, comment='청크길이'),
    sa.Column('start_position', sa.Integer(), nullable=True, comment='원본에서시작위치'),
    sa.Column('end_position', sa.Integer(), nullable=True, comment='원본에서끝위치'),
    sa.Column('page_number', sa.Integer(), nullable=True, comment='페이지번호'),
    sa.Column('embedding_vector', sa.LargeBinary(), nullable=True, comment='임베딩벡터'),
    sa.Column('vector_db_id', sa.String(length=100), nullable=True, comment='벡터DB청크아이디'),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True, comment='청크메타데이터'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_chunk', 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('document_processing_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='작업종류'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='우선순위'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='작업상태'),
    sa.Column('retry_count', sa.Integer(), nullable=True, comment='재시도횟수'),
    sa.Column('max_retries', sa.Integer(), nullable=True, comment='최대재시도횟수'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류메시지'),
    sa.Column('assigned_worker', sa.String(length=100), nullable=True, comment='할당된워커'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='시작일시'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='완료일시'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_priority', 'document_processing_queue', ['priority'], unique=False)
    op.create_index('idx_task_status', 'document_processing_queue', ['task_type', 'status'], unique=False)
    op.create_index(op.f('ix_document_processing_queue_id'), 'document_processing_queue', ['id'], unique=False)
    op.create_table('document_search_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='사용자ID'),
    sa.Column('search_query', sa.Text(), nullable=False, comment='검색어'),
    sa.Column('search_type', sa.String(length=20), nullable=True, comment='검색타입'),
    sa.Column('search_filters', sa.JSON(), nullable=True, comment='검색필터'),
    sa.Column('result_count', sa.Integer(), nullable=True, comment='검색결과수'),
    sa.Column('search_results', sa.JSON(), nullable=True, comment='검색결과ID목록'),
    sa.Column('response_time', sa.Integer(), nullable=True, comment='응답시간(ms)'),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_type', 'document_search_histories', ['search_type'], unique=False)
    op.create_index('idx_user_search_doc', 'document_search_histories', ['user_id', 'searched_at'], unique=False)
    op.create_index(op.f('ix_document_search_histories_id'), 'document_search_histories', ['id'], unique=False)
    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=50), nullable=False, comment='서비스명'),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True, comment='암호화된API키'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='사용여부'),
    sa.Column('usage_count', sa.Integer(), nullable=True, comment='사용횟수'),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True, comment='최종사용일시'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_service', 'user_api_keys', ['user_id', 'service_name'], unique=False)
    op.create_index(op.f('ix_user_api_keys_id'), 'user_api_keys', ['id'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='알림제목'),
    sa.Column('message', sa.Text(), nullable=True, comment='알림내용'),
    sa.Column('notification_type', sa.String(length=50), nullable=True, comment='알림종류'),
    sa.Column('related_bid_no', sa.String(length=50), nullable=True, comment='관련입찰공고번호'),
    sa.Column('is_read', sa.Boolean(), nullable=True, comment='읽음여부'),
    sa.Column('is_sent', sa.Boolean(), nullable=True, comment='발송여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_type', 'user_notifications', ['notification_type'], unique=False)
    op.create_index('idx_user_notification', 'user_notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_user_notifications_id'), 'user_notifications', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notification', sa.Boolean(), nullable=True, comment='이메일알림여부'),
    sa.Column('sms_notification', sa.Boolean(), nullable=True, comment='SMS알림여부'),
    sa.Column('push_notification', sa.Boolean(), nullable=True, comment='푸시알림여부'),
    sa.Column('interested_categories', sa.JSON(), nullable=True, comment='관심분야목록'),
    sa.Column('budget_range_min', sa.Integer(), nullable=True, comment='관심예산최소값'),
    sa.Column('budget_range_max', sa.Integer(), nullable=True, comment='관심예산최대값'),
    sa.Column('notification_time', sa.String(length=5), nullable=True, comment='알림받을시간'),
    sa.Column('notification_days', sa.JSON(), nullable=True, comment='알림받을요일'),
    sa.Column('ai_recommendation', sa.Boolean(), nullable=True, comment='AI추천여부'),
    sa.Column('success_prediction', sa.Boolean(), nullable=True, comment='성공률예측사용여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_table('user_search_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True, comment='검색어'),
    sa.Column('search_filters', sa.JSON(), nullable=True, comment='검색필터조건'),
    sa.Column('result_count', sa.Integer(), nullable=True, comment='검색결과수'),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='검색일시'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_search', 'user_search_histories', ['user_id', 'searched_at'], unique=False)
    op.create_index(op.f('ix_user_search_histories_id'), 'user_search_histories', ['id'], unique=False)
    op.create_table('bid_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_notice_no', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False, comment='업체명'),
    sa.Column('company_no', sa.String(length=20), nullable=True, comment='업체번호'),
    sa.Column('bid_amount', sa.DECIMAL(precision=15, scale=0), nullable=True, comment='입찰금액'),
    sa.Column('bid_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='입찰률'),
    sa.Column('bid_rank', sa.Integer(), nullable=True, comment='입찰순위'),
    sa.Column('is_winner', sa.Boolean(), nullable=True, comment='낙찰여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bid_notice_no'], ['bid_announcements.bid_notice_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_bid', 'bid_participants', ['company_no', 'bid_notice_no'], unique=False)
    op.create_index(op.f('ix_bid_participants_company_no'), 'bid_participants', ['company_no'], unique=False)
    op.create_index(op.f('ix_bid_participants_id'), 'bid_participants', ['id'], unique=False)
    op.create_table('bid_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_notice_no', sa.String(length=50), nullable=False),
    sa.Column('success_company', sa.String(length=200), nullable=True, comment='낙찰업체명'),
    sa.Column('success_company_no', sa.String(length=20), nullable=True, comment='낙찰업체번호'),
    sa.Column('success_amount', sa.DECIMAL(precision=15, scale=0), nullable=True, comment='낙찰금액'),
    sa.Column('success_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='낙찰률'),
    sa.Column('bid_participant_count', sa.Integer(), nullable=True, comment='입찰참가업체수'),
    sa.Column('bid_method_detail', sa.String(length=100), nullable=True, comment='낙찰방법'),
    sa.Column('contract_date', sa.DateTime(), nullable=True, comment='계약체결일'),
    sa.Column('contract_period', sa.String(length=100), nullable=True, comment='계약기간'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bid_notice_no'], ['bid_announcements.bid_notice_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_success_amount', 'bid_results', ['success_amount'], unique=False)
    op.create_index('idx_success_company', 'bid_results', ['success_company_no'], unique=False)
    op.create_index(op.f('ix_bid_results_id'), 'bid_results', ['id'], unique=False)
    op.create_index(op.f('ix_bid_results_success_company_no'), 'bid_results', ['success_company_no'], unique=False)
    op.create_table('contract_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_no', sa.String(length=50), nullable=True, comment='계약번호'),
    sa.Column('bid_notice_no', sa.String(length=50), nullable=True, comment='입찰공고번호'),
    sa.Column('contractor_name', sa.String(length=200), nullable=True, comment='계약자명'),
    sa.Column('contractor_no', sa.String(length=20), nullable=True, comment='계약자번호'),
    sa.Column('contract_name', sa.Text(), nullable=True, comment='계약명'),
    sa.Column('contract_amount', sa.DECIMAL(precision=15, scale=0), nullable=True, comment='계약금액'),
    sa.Column('contract_date', sa.DateTime(), nullable=True, comment='계약체결일'),
    sa.Column('contract_start_date', sa.DateTime(), nullable=True, comment='계약시작일'),
    sa.Column('contract_end_date', sa.DateTime(), nullable=True, comment='계약종료일'),
    sa.Column('contract_type', sa.String(length=50), nullable=True, comment='계약종류'),
    sa.Column('payment_method', sa.String(length=100), nullable=True, comment='대금지급방법'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bid_notice_no'], ['bid_announcements.bid_notice_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contract_date', 'contract_info', ['contract_date'], unique=False)
    op.create_index('idx_contractor', 'contract_info', ['contractor_no'], unique=False)
    op.create_index(op.f('ix_contract_info_contract_no'), 'contract_info', ['contract_no'], unique=True)
    op.create_index(op.f('ix_contract_info_contractor_no'), 'contract_info', ['contractor_no'], unique=False)
    op.create_index(op.f('ix_contract_info_id'), 'contract_info', ['id'], unique=False)
    op.create_table('user_bid_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bid_notice_no', sa.String(length=50), nullable=False),
    sa.Column('bookmark_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='북마크일시'),
    sa.Column('memo', sa.Text(), nullable=True, comment='메모'),
    sa.ForeignKeyConstraint(['bid_notice_no'], ['bid_announcements.bid_notice_no'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_bookmark', 'user_bid_bookmarks', ['user_id', 'bid_notice_no'], unique=False)
    op.create_index(op.f('ix_user_bid_bookmarks_id'), 'user_bid_bookmarks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bid_bookmarks_id'), table_name='user_bid_bookmarks')
    op.drop_index('idx_user_bookmark', table_name='user_bid_bookmarks')
    op.drop_table('user_bid_bookmarks')
    op.drop_index(op.f('ix_contract_info_id'), table_name='contract_info')
    op.drop_index(op.f('ix_contract_info_contractor_no'), table_name='contract_info')
    op.drop_index(op.f('ix_contract_info_contract_no'), table_name='contract_info')
    op.drop_index('idx_contractor', table_name='contract_info')
    op.drop_index('idx_contract_date', table_name='contract_info')
    op.drop_table('contract_info')
    op.drop_index(op.f('ix_bid_results_success_company_no'), table_name='bid_results')
    op.drop_index(op.f('ix_bid_results_id'), table_name='bid_results')
    op.drop_index('idx_success_company', table_name='bid_results')
    op.drop_index('idx_success_amount', table_name='bid_results')
    op.drop_table('bid_results')
    op.drop_index(op.f('ix_bid_participants_id'), table_name='bid_participants')
    op.drop_index(op.f('ix_bid_participants_company_no'), table_name='bid_participants')
    op.drop_index('idx_company_bid', table_name='bid_participants')
    op.drop_table('bid_participants')
    op.drop_index(op.f('ix_user_search_histories_id'), table_name='user_search_histories')
    op.drop_index('idx_user_search', table_name='user_search_histories')
    op.drop_table('user_search_histories')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_notifications_id'), table_name='user_notifications')
    op.drop_index('idx_user_notification', table_name='user_notifications')
    op.drop_index('idx_notification_type', table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_user_api_keys_id'), table_name='user_api_keys')
    op.drop_index('idx_user_service', table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_index(op.f('ix_document_search_histories_id'), table_name='document_search_histories')
    op.drop_index('idx_user_search_doc', table_name='document_search_histories')
    op.drop_index('idx_search_type', table_name='document_search_histories')
    op.drop_table('document_search_histories')
    op.drop_index(op.f('ix_document_processing_queue_id'), table_name='document_processing_queue')
    op.drop_index('idx_task_status', table_name='document_processing_queue')
    op.drop_index('idx_priority', table_name='document_processing_queue')
    op.drop_table('document_processing_queue')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index('idx_doc_chunk', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_bid_announcements_presumpt_price'), table_name='bid_announcements')
    op.drop_index(op.f('ix_bid_announcements_notice_inst_code'), table_name='bid_announcements')
    op.drop_index(op.f('ix_bid_announcements_is_urgent'), table_name='bid_announcements')
    op.drop_index(op.f('ix_bid_announcements_id'), table_name='bid_announcements')
    op.drop_index(op.f('ix_bid_announcements_demand_inst_code'), table_name='bid_announcements')
    op.drop_index(op.f('ix_bid_announcements_bid_status'), table_name='bid_announcements')
    op.drop_index(op.f('ix_bid_announcements_bid_notice_no'), table_name='bid_announcements')
    op.drop_index(op.f('ix_bid_announcements_bid_notice_date'), table_name='bid_announcements')
    op.drop_index(op.f('ix_bid_announcements_bid_close_date'), table_name='bid_announcements')
    op.drop_index(op.f('ix_bid_announcements_bid_class_no'), table_name='bid_announcements')
    op.drop_index('idx_search_text', table_name='bid_announcements')
    op.drop_index('idx_inst_combo', table_name='bid_announcements')
    op.drop_index('idx_budget_range', table_name='bid_announcements')
    op.drop_index('idx_bid_date_status', table_name='bid_announcements')
    op.drop_table('bid_announcements')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_company_reg', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index('idx_file_type_status', table_name='documents')
    op.drop_index('idx_document_type', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###