# Alembic 설정 파일

[alembic]
# 마이그레이션 스크립트 경로
script_location = alembic

# 마이그레이션 파일 명명 규칙
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s_%%(slug)s

# sys.path 경로, sqlalchemy.url 를 resolve하기 위해 필요
# (이 디렉토리는 PYTHONPATH에 포함되어야 함)
prepend_sys_path = .

# 환경 설정
sqlalchemy.url = sqlite:///./test.db

# 로그 레벨
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S