"""Add user and subscription models

Revision ID: 0d1f5b5c537d
Revises: 26e60c6557e7
Create Date: 2025-09-17 00:19:40.681756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1f5b5c537d'
down_revision: Union[str, None] = '26e60c6557e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###